[package]
name = "py_msvc_demangler"
version = "0.0.1"
authors = ["Andrew V. Teylu <andrew@tey.lu>"]
edition = "2021"

[lib]
name = "msvc_demangler"
crate-type = ["cdylib"]

[dependencies]
msvc-demangler = "0.9.0"

[dependencies.pyo3]
version = "0.17.3"
features = ["extension-module"]
